name: Generate Android APK Release

on: 
  push:
    tags:
    - '*'
  
jobs:
  releases:
    name: release apk
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "12.0"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: $
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test
      - run: flutter build apk --release
      - uses: ncipollo/release-action@v1
        with:
         artifacts: "build/app/outputs/flutter-apk/*.apk"
         token: $
